import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { updateList, selectList, deleteItem } from "./slices/ListSlice";
import { useDispatch, useSelector } from "react-redux";

export default function Home() {
  const dispatch = useDispatch();
  const { list } = useSelector(selectList);
  const [userInput, setUserInput] = useState("");

  const onHandleChange = (e) => {
    e.preventDefault();
    setUserInput(e.target.value);
  };

  const onHandleSubmit = (e) => {
    e.preventDefault();
    dispatch(updateList(userInput));
    setUserInput("");
  };

  const onHandleDelete = (todo) => {
    const newList = list.filter(
      (listItem) => list.indexOf(listItem) != list.indexOf(todo)
    );
    dispatch(deleteItem(newList));
  };

  return (
    <div style={{ backgroundColor: "white" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form>
        <input type={"text"} value={userInput} onChange={onHandleChange} />
        <button onClick={onHandleSubmit}>Submit</button>
      </form>

      {list && list !== null && (
        <ul>
          {list?.map((item, index) => {
            return (
              <>
                <li key={index}>{item}</li>
                <button onClick={() => onHandleDelete(item)}>Delete</button>
              </>
            );
          })}
        </ul>
      )}
    </div>
  );
}
