import { useState } from "react";
import Head from "next/head";

export default function Home() {
  const [userInput, setUserInput] = useState("");
  const [movies, setMovies] = useState([]);

  const onHandleChange = (e) => {
    e.preventDefault();
    setUserInput(e.target.value);
  };

  const onHandleSubmit = (e) => {
    e.preventDefault();
    const options = {
      method: "GET",
    };

    fetch(
      `https://fake-movie-database-api.herokuapp.com/api?s=${userInput}`,
      options
    )
      .then((response) => response.json())
      .then(({ Search }) => setMovies(Search))
      .catch((err) => console.error(err));
  };

  return (
    <div style={{ backgroundColor: "white" }}>
      <Head>
        <title>Movie Database</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form style={{ padding: "10px" }}>
        <input
          type={"text"}
          value={userInput}
          onChange={onHandleChange}
          placeholder="batman or star war only"
          style={{ height: "40px", width: "300px" }}
        />
        <button
          onClick={onHandleSubmit}
          style={{ height: "40px", width: "100px", marginLeft: "10px" }}
        >
          Submit
        </button>
      </form>

      <table border={"1px"} style={{ width: "100%" }}>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Year</th>
          <th>Poster</th>
        </tr>
        {movies !== 0 &&
          movies.map((item) => (
            <tr key={item.imdbID}>
              <td>{item.imdbID}</td>
              <td>{item.Title}</td>
              <td>{item.Year}</td>
              <td>
                <img
                  src={
                    item.Poster ||
                    "https://s.studiobinder.com/wp-content/uploads/2017/12/Movie-Poster-Template-Dark-with-Image.jpg?x81279"
                  }
                  alt="poster"
                  style={{ width: "50px", height: "50px" }}
                />
              </td>
            </tr>
          ))}
      </table>
    </div>
  );
}
